# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["**"]
    tags-ignore: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install
      - name: Run type check
        run: yarn type-check
      - name: Run lint
        run: yarn lint
      - name: Run test
        run: yarn test
      - name: Run build
        run: yarn build
      # - name: Coveralls GitHub Action
      #   uses: coverallsapp/github-action@v1.1.1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
